### ISSUE TITLE
Flutter example Stream.listen

### ISSUE THREAD

**Issue by theobouwman** [alexeieleusis/greencat#16]
In found that in the Flutter example's `initState()` method there is a listener on the stream of the store's state object:
```dart
store.stream.listen((AuthState state) {
   setState(() {
     _googleSignInAccount = state.googleSignInAccount; // my own state property
   });
});
```

should I use this mechanism to for example rebuild a list of items when the list changes?

**Comment by alexeieleusis** [comment]
Probably, but sounds like an overkill, Isn't there any other way to keep that reference? I would at least filter for different instances.

The flutter example is quite outdated, I need to relearn Flutter and update it.
