### ISSUE TITLE
Upgrade from comment-based generics syntax

### ISSUE THREAD

**Issue by srawlins** [alexeieleusis/greencat#21]
The comment-based generics syntax will be removed from the Dart SDK tools (like DDC, analyzer) "soon." dart-lang/sdk#28796

Such syntax (like in [combineWith](https://github.com/alexeieleusis/greencat/blob/master/lib/src/reducer_base.dart#L13)) needs to be updated, and the minimum Dart SDK in pubspec.yaml needs to be bumped to 1.21, when the [real, non-comment-based syntax was introduced](http://news.dartlang.org/2016/12/dart-121-generic-method-syntax.html).

**Comment by alexeieleusis** [comment]
Thank you for the report @srawlins
